baseURL = "https://example.org/"
languageCode = "zh-cn"
title = "我的个人博客"
theme = "PaperMod"

[params]
  defaultTheme = "auto" # auto, dark, light
  ShowShareButtons = true
  ShowReadingTime = true
  ShowPostNavLinks = true
